### ISSUE TITLE
model checkpoints

### ISSUE THREAD

**Issue by SaharHusseini** [Orange-OpenSource/AIVC#7]
Hello,

I tried to clone the repo, but I got the following error.

Downloading models/ms_ssim-2021cc-1/0_model.pt (164 MB)
Error downloading object: models/ms_ssim-2021cc-1/0_model.pt (43f4625): Smudge error: Error downloading models/ms_ssim-2021cc-1/0_model.pt (43f4625ad0294be5ac745e2410f2c0c4e6e2f08dafcf94999564e5cf306c93ff): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

I think I am not able to fetch the model checkpoints. Is it possible to share the checkpoints another way?

=========================below is the error================================
                    ********************************************************************************                    
                                                   Starting encoding                                                    
Using /homes/husseini/.cache/torch_extensions/py310_cu116 as PyTorch extensions root...
Emitting ninja build file /homes/husseini/.cache/torch_extensions/py310_cu116/torchac_backend/build.ninja...
Building extension module torchac_backend...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module torchac_backend...
[STATE] Start processing: yuv -> png
        Input file:                            ../raw_videos/BlowingBubbles_416x240_50_420.yuv
        Output directory:                      ../raw_videos/BlowingBubbles_416x240_50_420/
        Number of frames in the video:         101
        Frame:                                 101 / 101
[STATE] End processing: yuv -> png
[STATE] End processing
[INFO]     | Seed                        |                             | 666
Traceback (most recent call last):
  File "/medias/Sahar/AIVC/src/encode.py", line 103, in <module>
    model = load_model(prefix='0_', on_cpu=True).to(COMPUTE_PARAM.get('device')).eval()
  File "/medias/Sahar/AIVC/src/model_mngt/model_management.py", line 347, in load_model
    model = torch.load('./' + prefix + 'model.pt', map_location=map_loc)
  File "//medias/Sahar/env/image_compression/lib/python3.10/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "//medias/Sahar/env/image_compression/lib/python3.10/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
                    ********************************************************************************                    
                                                   Starting decoding                                                    
Using /homes/husseini/.cache/torch_extensions/py310_cu116 as PyTorch extensions root...
Emitting ninja build file /homes/husseini/.cache/torch_extensions/py310_cu116/torchac_backend/build.ninja...
Building extension module torchac_backend...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module torchac_backend...
Traceback (most recent call last):
  File "/medias/Sahar/AIVC/src/decode.py", line 56, in <module>
    model = load_model(prefix='0_', on_cpu=True).to(COMPUTE_PARAM.get('device')).eval()
  File "/medias/Sahar/AIVC/src/model_mngt/model_management.py", line 347, in load_model
    model = torch.load('./' + prefix + 'model.pt', map_location=map_loc)
  File "//medias/Sahar/env/image_compression/lib/python3.10/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "//medias/Sahar/env/image_compression/lib/python3.10/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
                    ********************************************************************************                    
                                                  Starting evaluation                                                   
/medias/Sahar/AIVC/src/clic21/metrics.py:50: RuntimeWarning: invalid value encountered in scalar divide
  results['PSNR'] = mse2psnr(np.sum(sqerror_values) / num_dims)
/medias/Sahar/AIVC/src/clic21/metrics.py:52: RuntimeWarning: invalid value encountered in scalar divide
  results['MSSSIM'] = np.sum(msssim_values) / num_dims
PSNR    [dB]: nan
MS-SSIM     : nan
MS-SSIM [dB]: nan
[ERROR]: bitstream not found, can not evaluate its size!
Bistream path: ../bitstream.bin
Traceback (most recent call last):
  File "/medias/Sahar/AIVC/src/evaluate.py", line 78, in <module>
    print('Size [bytes]: ' + '%.0f' % (size_bytes))
NameError: name 'size_bytes' is not defined

**Comment by theoladune** [comment]
Hello,

We do have an issue with the storage of our pre-trained models. We're looking for a more convenient solutions to share the models. I'll come back to you as soon as the models are available.
Sorry for the inconvenience...

**Comment by LinYuJu120** [comment]
Hi,

I have exactly the same problem , I would like to ask if there is a solution now~

**Comment by LinYuJu120** [comment]
Have anyone can help me with this issue!? Thanks~

**Comment by PierceLovesee** [comment]
Hi, 

Facing the same issue.  Is this repo still being maintained?

**Comment by theoladune** [comment]
Hello everyone,

Sorry for the inconvenience due to the limitation of git LFS bandwidth...

As a short term fix, the bandwidth should be 10x higher (from 1 GB to 10 GB) from September 1st, which should be a temporary answer to this issue. 

Since this problem seems more common than I initially thought, I'll ask for a significant increase of the bandwidth associated to this repository.

**Comment by topriss** [comment]
Hi,

The same issue happens again.
Is this repo still being maintained?

Thank you!

**Comment by huu4ontocord** [comment]
Hi everyone,

Does anyone have this model and can push it to HF?

We can't seem to download it via lfs anymore.

@topriss @theoladune @PierceLovesee @LinYuJu120 @SaharHusseini 

Thank you!

**Comment by abetday** [comment]
I have same problem? 
how can I solve it ?

**Comment by dkowsikpai** [comment]
Hi everyone,

We are looking forward to a fast resolution of the model download issue. Will it be possible to share through Huggingface or any other online storage drives (Google Drive, Onedrive etc...)?

@topriss @theoladune @PierceLovesee @LinYuJu120 @SaharHusseini

Thank you!

**Comment by benjaminherb** [comment]
Hi

I am also interested in this project and stuck on the LFS limitation. 
Has anyone found a way around it?

Thank you!

**Comment by theoladune** [comment]
Hello :wave:

The AIVC repository is now outdated and will be archived, as no further maintenance is planned. Since the pre-trained models no longer offer sufficiently good performance compared to other models from the literature, they will not be made available.

I encourage you to explore our more recent our more recent work instead. The [Cool-chic](https://github.com/Orange-OpenSource/Cool-Chic) neural video codec, which is a low-complexity alternative to the autoencoder-based codecs.
